name: CI for C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check code formatting
        run: |
          set -e
          if ! find . -regex '.*\.[ch]' -exec clang-format -style=Google --dry-run --Werror {} +; then
            echo "Code formatting check failed. Please run 'make format' to fix formatting issues."
            exit 1
          fi
          echo "Code formatting check passed."

      - name: Build and test
        run: |
          set -e
          make clean
          make
          make tests
          echo "Build and tests completed successfully."

      - name: Cleanup
        if: always()
        run: |
          make clean
          echo "Cleanup completed."
