name: Continuous Integration for Hash Table and Pool Allocator Project

on:
  push:
    branches:
      - main
      - hash_table
  pull_request:
    branches:
      - main
      - hash_table

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make clang-format

      - name: Check code formatting
        run: |
          set -e
          # Форматируем все .c и .h файлы по стандарту LLVM
          find . -regex '.*\.[ch]' -exec clang-format -style=LLVM -i {} +
          # Проверяем, что форматирование соответствует стандарту
          find . -regex '.*\.[ch]' -exec clang-format -style=LLVM --dry-run --Werror {} +

      - name: Clean build artifacts
        run: make clean

      - name: Build project
        run: make

      - name: Run tests
        run: make tests

      - name: Cleanup after execution
        run: make clean
