name: Main CI-pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-format gcc make

      - name: Checkstyle
        run: make check_fmt

      - name: Tests
        run: make tests

      - name: Cleanup
        if: always()
        run: make clean
